// src/views/UserView.vue
<script setup>
import { ref, computed, onMounted, inject } from 'vue';
import { useRoute } from 'vue-router';
import { api } from '../services/api';
import { CheckSquare, Save, Copy, Edit, Trash2 } from 'lucide-vue-next';

const toast = inject('toast');

const route = useRoute();
const activityId = route.query.id;

const isLoading = ref(true);
const error = ref('');
const activity = ref(null);
const members = ref([]);
const transactions = ref([]);

// Form State
const itemName = ref('');
const paidById = ref('');
const amount = ref('');
const involvedMemberIds = ref([]);
const isSubmitting = ref(false);
const editingTransactionId = ref(null);

const isRecapModalOpen = ref(false);
const selectedRecapMemberId = ref('');
const tempRecapMemberId = ref('');

const confirmRecapMember = () => {
  if (tempRecapMemberId.value) {
    selectedRecapMemberId.value = tempRecapMemberId.value;
    isRecapModalOpen.value = false;
  }
};

const recapData = computed(() => {
  if (!selectedRecapMemberId.value || !transactions.value.length || !members.value.length) return null;
  
  const member = members.value.find(m => String(m.id) === String(selectedRecapMemberId.value));
  if (!member) return null;
  
  const items = [];
  let total = 0;
  
  transactions.value.forEach(t => {
    const involved = t.involved_member_ids ? String(t.involved_member_ids).split(',') : [];
    if (involved.includes(String(member.id))) {
      const splitAmt = Number(t.amount) / involved.length;
      items.push({
        name: t.item_name || '-',
        amount: splitAmt
      });
      total += splitAmt;
    }
  });
  
  return {
    member: member,
    items: items,
    total: total
  };
});

const fetchData = async () => {
  if (!activityId) {
    isLoading.value = false;
    return;
  }
  
  isLoading.value = true;
  error.value = '';
  try {
    const res = await api.getActivity(activityId);
    if (res.success) {
      activity.value = res.data.activity;
      members.value = res.data.members;
      transactions.value = res.data.transactions;
    } else {
      error.value = res.error || 'Kegiatan tidak ditemukan.';
    }
  } catch (err) {
    error.value = 'Gagal memuat data dari server.';
    console.error(err);
  } finally {
    isLoading.value = false;
  }
};

onMounted(() => {
  fetchData();
});

// Calculate statistics
const topContributor = computed(() => {
  if (!transactions.value.length || !members.value.length) return null;
  const contributions = {};
  transactions.value.forEach(t => {
    contributions[t.paid_by_member_id] = (contributions[t.paid_by_member_id] || 0) + Number(t.amount);
  });
  
  let topId = null;
  let maxAmount = 0;
  for (const [id, amt] of Object.entries(contributions)) {
    if (amt > maxAmount) {
      maxAmount = amt;
      topId = id;
    }
  }
  
  const member = members.value.find(m => String(m.id) === String(topId));
  return member ? { name: member.name, amount: maxAmount } : null;
});

const totalExpense = computed(() => {
  return transactions.value.reduce((sum, t) => sum + Number(t.amount), 0);
});

// Calculate Top Spenders
const spendersRanking = computed(() => {
  if (!transactions.value.length || !members.value.length) return [];
  
  const expenses = {};
  members.value.forEach(m => expenses[m.id] = 0);
  
  transactions.value.forEach(t => {
    const amt = Number(t.amount);
    const involved = t.involved_member_ids ? String(t.involved_member_ids).split(',') : [];
    if (involved.length === 0) return;
    const splitAmt = amt / involved.length;
    
    involved.forEach(id => {
      if (expenses[id] !== undefined) {
        expenses[id] += splitAmt;
      }
    });
  });
  
  return members.value
    .map(m => ({ id: m.id, name: m.name, amount: expenses[m.id] }))
    .filter(m => m.amount > 0)
    .sort((a, b) => b.amount - a.amount);
});

// Settlement Algorithm (Debt Simplification)
const settlements = computed(() => {
  if (!transactions.value.length || !members.value.length) return [];
  
  // Calculate net balances for each member
  const balances = {};
  members.value.forEach(m => balances[m.id] = 0);
  
  transactions.value.forEach(t => {
    const amt = Number(t.amount);
    const involved = t.involved_member_ids ? String(t.involved_member_ids).split(',') : [];
    const splitAmt = amt / involved.length;
    
    // Payer gets positive balance
    if (balances[t.paid_by_member_id] !== undefined) {
      balances[t.paid_by_member_id] += amt;
    }
    
    // Involved get negative balance
    involved.forEach(id => {
      if (balances[id] !== undefined) {
        balances[id] -= splitAmt;
      }
    });
  });
  
  // Separate into debtors (negative balance) and creditors (positive balance)
  const debtors = [];
  const creditors = [];
  
  for (const [id, bal] of Object.entries(balances)) {
    if (bal < -0.01) debtors.push({ id, amount: -bal });
    else if (bal > 0.01) creditors.push({ id, amount: bal });
  }
  
  // Sort by amount descending to minimize transactions
  debtors.sort((a, b) => b.amount - a.amount);
  creditors.sort((a, b) => b.amount - a.amount);
  
  const results = [];
  let d = 0;
  let c = 0;
  
  while (d < debtors.length && c < creditors.length) {
    const debtor = debtors[d];
    const creditor = creditors[c];
    
    const minAmount = Math.min(debtor.amount, creditor.amount);
    
    const debtorObj = members.value.find(m => String(m.id) === String(debtor.id));
    const creditorObj = members.value.find(m => String(m.id) === String(creditor.id));
    
    if (debtorObj && creditorObj) {
      results.push({
        from: debtorObj.name,
        to: creditorObj.name,
        amount: minAmount,
        bankName: creditorObj.bank_name,
        bankAccount: creditorObj.bank_account
      });
    }
    
    debtor.amount -= minAmount;
    creditor.amount -= minAmount;
    
    if (debtor.amount < 0.01) d++;
    if (creditor.amount < 0.01) c++;
  }
  
  return results;
});

const formatCurrency = (amount) => {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(amount);
};

const selectAllInvolved = () => {
  if (involvedMemberIds.value.length === members.value.length) {
    involvedMemberIds.value = [];
  } else {
    involvedMemberIds.value = members.value.map(m => m.id);
  }
};

const submitTransaction = async () => {
  if (!paidById.value || !amount.value || involvedMemberIds.value.length === 0) {
    toast("Mohon lengkapi form transaksi.", "error");
    return;
  }
  
  isSubmitting.value = true;
  try {
    let res;
    if (editingTransactionId.value) {
      res = await api.editTransaction({
        transaction_id: editingTransactionId.value,
        item_name: itemName.value,
        paid_by_member_id: paidById.value,
        amount: amount.value,
        involved_member_ids: involvedMemberIds.value
      });
    } else {
      res = await api.addTransaction({
        activity_id: activityId,
        item_name: itemName.value,
        paid_by_member_id: paidById.value,
        amount: amount.value,
        involved_member_ids: involvedMemberIds.value
      });
    }
    
    if (res.success) {
      cancelEditTransaction();
      await fetchData();
      toast("Transaksi berhasil disimpan!", "success");
    } else {
      toast("Gagal menyimpan transaksi: " + res.error, "error");
    }
  } catch (err) {
    toast("Terjadi kesalahan koneksi.", "error");
    console.error(err);
  } finally {
    isSubmitting.value = false;
  }
};

const deleteTransaction = async (id) => {
  if (confirm('Yakin ingin menghapus pengeluaran ini?')) {
    try {
      const res = await api.deleteTransaction(id);
      if (res.success) {
        toast("Transaksi berhasil dihapus.", "success");
        await fetchData();
      } else {
        toast('Gagal menghapus: ' + (res.error || 'Unknown error'), 'error');
      }
    } catch (err) {
      toast('Terjadi kesalahan koneksi.', 'error');
    }
  }
};

const editTransaction = (t) => {
  editingTransactionId.value = t.id;
  itemName.value = t.item_name && t.item_name !== '-' ? t.item_name : '';
  paidById.value = t.paid_by_member_id;
  amount.value = t.amount;
  involvedMemberIds.value = t.involved_member_ids ? String(t.involved_member_ids).split(',') : [];
  window.scrollTo({ top: 0, behavior: 'smooth' });
};

const cancelEditTransaction = () => {
  editingTransactionId.value = null;
  itemName.value = '';
  paidById.value = '';
  amount.value = '';
  involvedMemberIds.value = [];
};

const copyAccount = (account) => {
  if (!account) return;
  navigator.clipboard.writeText(account);
  toast("Nomor rekening disalin!", "success");
};
</script>

<template>
  <div>
    <!-- Landing Page -->
    <div v-if="!activityId" class="text-center" style="padding: 3rem 1rem;">
      <h2 style="color: var(--primary); margin-bottom: 1rem; font-size: 2rem;">Selamat Datang di SplitBill</h2>
      <p style="color: var(--text-muted); margin-bottom: 2.5rem; font-size: 1.125rem;">Bagi tagihan bersama teman jadi lebih mudah dan transparan.</p>
      
      <div class="card" style="max-width: 400px; margin: 0 auto; background: var(--surface);">
        <h3 style="margin-bottom: 1rem; font-size: 1.25rem;">Area Admin</h3>
        <p style="margin-bottom: 1.5rem; color: var(--text-muted); font-size: 0.875rem;">Buat kegiatan baru atau kelola kegiatan yang sudah ada.</p>
        <router-link to="/admin" class="btn btn-primary btn-block" style="padding: 0.75rem;">
          Masuk ke Laman Admin
        </router-link>
      </div>
    </div>

    <div v-else-if="isLoading" class="text-center" style="padding: 3rem;">
      <p>Memuat data kegiatan...</p>
    </div>
    
    <div v-else-if="error" class="card" style="border-color: var(--danger);">
      <h3 class="text-danger">Oops!</h3>
      <p>{{ error }}</p>
    </div>
    
    <div v-else-if="activity">
      <div style="margin-bottom: 2rem;">
        <h2 style="font-size: 1.75rem; color: var(--primary);">{{ activity.name }}</h2>
        <span class="badge" :class="activity.status === 'finished' ? 'badge-finished' : 'badge-active'">
          {{ activity.status === 'finished' ? 'Selesai' : 'Sedang Berjalan' }}
        </span>
      </div>

      <!-- Dashboard Cards -->
      <div class="summary-cards-container mb-4">
        <div class="card summary-card" style="background: linear-gradient(135deg, #f79039, #e65c00); color: white;">
          <h4>Total Pengeluaran</h4>
          <div class="amount">{{ formatCurrency(totalExpense) }}</div>
        </div>
        <div class="card summary-card" style="background: linear-gradient(135deg, #10B981, #059669); color: white;">
          <h4>Kontributor Terbanyak</h4>
          <div v-if="topContributor">
            <div class="amount" style="font-size: 1.25rem;">{{ topContributor.name }}</div>
            <div style="font-size: 0.875rem; opacity: 0.9;">{{ formatCurrency(topContributor.amount) }}</div>
          </div>
          <div v-else style="opacity: 0.8;">Belum ada</div>
        </div>
      </div>

      <!-- Recap Trigger -->
      <div class="card mb-4 text-center" style="background: var(--surface);">
        <p class="mb-3 font-semibold text-secondary">Ingin melihat rincian belanjamu?</p>
        <button class="btn btn-secondary" @click="isRecapModalOpen = true">Klik Disini</button>
      </div>

      <!-- Recap Table -->
      <div class="card mb-4" v-if="recapData">
        <div class="recap-header">
          <h3 class="card-title mb-0">Rekap Belanjaan: {{ recapData.member.name }}</h3>
          <button class="btn btn-secondary btn-sm" @click="selectedRecapMemberId = ''">Tutup</button>
        </div>
        <div style="overflow-x: auto;">
          <table style="width: 100%; border-collapse: collapse; text-align: left; min-width: 300px;">
            <thead>
              <tr style="border-bottom: 1px solid var(--border);">
                <th style="padding: 0.75rem; font-weight: 600;">Nama Aktivitas</th>
                <th style="padding: 0.75rem; font-weight: 600; text-align: right;">Biaya</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(item, idx) in recapData.items" :key="idx" style="border-bottom: 1px solid var(--border);">
                <td style="padding: 0.75rem;">{{ item.name }}</td>
                <td style="padding: 0.75rem; text-align: right;">{{ formatCurrency(item.amount) }}</td>
              </tr>
              <tr v-if="recapData.items.length === 0">
                <td colspan="2" style="padding: 1rem; text-align: center; color: var(--secondary);">Tidak ada pengeluaran.</td>
              </tr>
            </tbody>
            <tfoot>
              <tr>
                <td style="padding: 0.75rem; font-weight: 700;">Total</td>
                <td style="padding: 0.75rem; text-align: right; font-weight: 700; color: var(--danger);">{{ formatCurrency(recapData.total) }}</td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>

      <!-- Add Transaction Form -->
      <div class="card mb-4" v-if="activity.status !== 'finished'">
        <h3 class="card-title">{{ editingTransactionId ? 'Edit Pengeluaran' : 'Catat Pengeluaran' }}</h3>
        
        <div class="form-group">
          <label class="form-label">Nama Item / Keperluan</label>
          <input type="text" v-model="itemName" class="form-control" placeholder="Contoh: Tiket Masuk, Makan Siang">
        </div>

        <div class="form-group">
          <label class="form-label">Dibayar Oleh</label>
          <select v-model="paidById" class="form-control">
            <option value="" disabled>Pilih Anggota</option>
            <option v-for="m in members" :key="m.id" :value="m.id">{{ m.name }}</option>
          </select>
        </div>
        
        <div class="form-group">
          <label class="form-label">Besaran (Rp)</label>
          <input type="number" v-model="amount" class="form-control" placeholder="Contoh: 150000">
        </div>
        
        <div class="form-group">
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem;">
            <label class="form-label" style="margin-bottom: 0;">Yang Terlibat</label>
            <button class="btn btn-secondary" style="padding: 0.25rem 0.5rem; font-size: 0.75rem;" @click="selectAllInvolved">
              <CheckSquare :size="14" /> Pilih Semua
            </button>
          </div>
          <div class="checkbox-grid">
            <label v-for="m in members" :key="'inv'+m.id" class="toggle-switch">
              <input type="checkbox" :value="m.id" v-model="involvedMemberIds">
              <span class="toggle-slider"></span>
              <span class="toggle-label">{{ m.name }}</span>
            </label>
          </div>
        </div>
        
        <div style="display: flex; gap: 1rem; flex-direction: column;" class="mt-4 form-actions">
          <button class="btn btn-primary" style="flex: 1;" @click="submitTransaction" :disabled="isSubmitting">
            <Save :size="20" v-if="!isSubmitting" />
            {{ isSubmitting ? 'Menyimpan...' : 'Simpan Transaksi' }}
          </button>
          <button v-if="editingTransactionId" class="btn btn-secondary" style="flex: 1;" @click="cancelEditTransaction" :disabled="isSubmitting">
            Batal
          </button>
        </div>
      </div>

      <!-- Transaction List -->
      <div class="card mb-4" v-if="transactions.length > 0">
        <h3 class="card-title">Daftar Pengeluaran</h3>
        <div class="transaction-list">
          <div v-for="t in transactions" :key="t.id" class="transaction-item mb-3 p-3" style="border: 1px solid var(--border); border-radius: 8px;">
            <div class="transaction-header">
              <div>
                <div style="font-weight: 600;">
                  {{ members.find(m => String(m.id) === String(t.paid_by_member_id))?.name || 'Unknown' }}
                  membayar
                  <span style="color: var(--danger);">{{ formatCurrency(t.amount) }}</span>
                  untuk {{ t.item_name || '-' }}
                </div>
                <div style="font-size: 0.875rem; color: var(--secondary); margin-top: 0.25rem;">
                  Untuk: 
                  {{ 
                    (t.involved_member_ids ? String(t.involved_member_ids).split(',') : [])
                      .map(id => members.find(m => String(m.id) === String(id))?.name || id)
                      .join(', ')
                  }}
                </div>
              </div>
              
              <div style="display: flex; gap: 0.5rem;" v-if="activity.status !== 'finished'">
                <button @click="editTransaction(t)" class="btn btn-secondary btn-sm" style="color: var(--primary);" title="Edit">
                  <Edit :size="16" />
                </button>
                <button @click="deleteTransaction(t.id)" class="btn btn-secondary btn-sm" style="color: var(--danger);" title="Hapus">
                  <Trash2 :size="16" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Top Spenders Ranking -->
      <div class="card mb-4" v-if="spendersRanking.length > 0">
        <h3 class="card-title">Ranking Pengeluaran Terbanyak</h3>
        <p class="text-muted mb-4" style="font-size: 0.875rem;">Urutan anggota berdasarkan total tagihan (pengeluaran).</p>
        
        <div class="ranking-list">
          <div v-for="(spender, index) in spendersRanking" :key="spender.id" class="ranking-item">
            <div class="ranking-rank">
              <span v-if="index === 0" style="font-size: 1.5rem;" title="Peringkat 1">🥇</span>
              <span v-else-if="index === 1" style="font-size: 1.5rem;" title="Peringkat 2">🥈</span>
              <span v-else-if="index === 2" style="font-size: 1.5rem;" title="Peringkat 3">🥉</span>
              <span v-else class="rank-number">{{ index + 1 }}</span>
            </div>
            <div class="ranking-name" style="flex: 1; font-weight: 600;">{{ spender.name }}</div>
            <div class="ranking-amount" style="font-weight: 700; color: var(--danger);">{{ formatCurrency(spender.amount) }}</div>
          </div>
        </div>
      </div>

      <!-- Settlement List -->
      <div class="card">
        <h3 class="card-title">Hasil Pembagian (Settlement)</h3>
        <p class="text-muted mb-4" style="font-size: 0.875rem;">Siapa bayar ke siapa secara ringkas.</p>
        
        <div v-if="settlements.length === 0" class="text-center text-muted py-4">
          Belum ada tagihan.
        </div>
        
        <div v-else class="settlement-list">
          <div v-for="(s, idx) in settlements" :key="idx" class="settlement-item">
            <div class="settlement-info">
              <div class="settlement-names">
                <strong>{{ s.from }}</strong> <span style="color:var(--text-muted);">bayar ke</span> <strong>{{ s.to }}</strong>
              </div>
              <div class="settlement-amount">{{ formatCurrency(s.amount) }}</div>
            </div>
            
            <div v-if="s.bankAccount" class="settlement-action">
              <div class="account-badge">
                <span class="badge-orange">{{ s.bankName || 'Rekening/E-Wallet' }}</span>
                {{ s.bankAccount }}
              </div>
              <button class="btn btn-secondary btn-sm" @click="copyAccount(s.bankAccount)">
                <Copy :size="14" /> Copy
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Modal Select Member for Recap -->
      <div v-if="isRecapModalOpen" class="modal-overlay" @click.self="isRecapModalOpen = false">
        <div class="modal-content card">
          <h3 class="card-title">Pilih Anggota</h3>
          <p class="text-muted mb-4">Siapa yang ingin dilihat rekap belanjanya?</p>
          <div class="form-group">
            <select v-model="tempRecapMemberId" class="form-control">
              <option value="" disabled>Pilih Anggota</option>
              <option v-for="m in members" :key="m.id" :value="m.id">{{ m.name }}</option>
            </select>
          </div>
          <div style="display: flex; gap: 0.5rem; justify-content: flex-end; margin-top: 1.5rem;">
            <button class="btn btn-secondary" @click="isRecapModalOpen = false">Batal</button>
            <button class="btn btn-primary" @click="confirmRecapMember">Lihat Rekap</button>
          </div>
        </div>
      </div>

    </div>
  </div>
</template>

<style scoped>
.badge {
  display: inline-block;
  padding: 0.25rem 0.75rem;
  border-radius: 99px;
  font-size: 0.75rem;
  font-weight: 600;
}
.badge-active { background: #DBEAFE; color: #1E40AF; }
.badge-finished { background: #F3F4F6; color: #4B5563; }

.summary-card h4 {
  font-size: 0.875rem;
  font-weight: 500;
  opacity: 0.9;
  margin-bottom: 0.5rem;
}
.summary-card .amount {
  font-size: 1.75rem;
  font-weight: 700;
}

.checkbox-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
  gap: 1rem;
  background: #F8FAFC;
  padding: 1.25rem;
  border-radius: 8px;
  border: 1px solid var(--border);
}

/* Remove old checkbox styles */

.ranking-list {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
.ranking-item {
  display: flex;
  align-items: center;
  background: var(--background);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 0.75rem 1rem;
  gap: 1rem;
}
.ranking-rank {
  width: 32px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.rank-number {
  background: var(--surface);
  color: var(--secondary);
  font-weight: 700;
  border-radius: 50%;
  width: 28px;
  height: 28px;
  display: flex;
  justify-content: center;
  align-items: center;
  border: 1px solid var(--border);
  font-size: 0.875rem;
}

.settlement-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
.settlement-item {
  background: var(--background);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem;
}
.settlement-info {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  margin-bottom: 0.75rem;
}
@media (min-width: 640px) {
  .settlement-info {
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.5rem;
  }
}
.settlement-amount {
  font-weight: 700;
  color: var(--danger);
}
.settlement-action {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  background: var(--surface);
  padding: 0.5rem;
  border-radius: 6px;
  border: 1px dashed var(--border);
}
.account-badge {
  font-family: monospace;
  font-size: 0.875rem;
  flex: 1;
}
.badge-orange {
  background-color: #f97316;
  color: white;
  padding: 0.15rem 0.5rem;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 600;
  margin-right: 0.5rem;
  display: inline-block;
}
.btn-sm {
  padding: 0.25rem 0.5rem;
  font-size: 0.75rem;
}

/* Responsive Overrides */
.summary-cards-container {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1rem;
}

.transaction-header {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.recap-header {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  margin-bottom: 1rem;
  align-items: flex-start;
}

.form-actions {
  flex-direction: column;
}

@media (min-width: 640px) {
  .summary-cards-container {
    grid-template-columns: 1fr 1fr;
  }
  .transaction-header {
    flex-direction: row;
    justify-content: space-between;
    align-items: flex-start;
  }
  .recap-header {
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
  }
  .form-actions {
    flex-direction: row;
  }
}

.modal-overlay {
  position: fixed;
  top: 0; left: 0; right: 0; bottom: 0;
  background: rgba(0,0,0,0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
  padding: 1rem;
}
.modal-content {
  width: 100%;
  max-width: 400px;
  background: var(--background);
  box-shadow: 0 10px 25px rgba(0,0,0,0.2);
}
</style>

// src/pages/UserView.jsx
import React, { useState, useEffect, useMemo } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { api } from '../services/api';
import { CheckSquare, Save, Copy, Edit, Trash2 } from 'lucide-react';
import { useToast } from '../App';

export default function UserView() {
  const toast = useToast();
  const [searchParams] = useSearchParams();
  const activityId = searchParams.get('id');

  const [activity, setActivity] = useState(null);
  const [members, setMembers] = useState([]);
  const [transactions, setTransactions] = useState([]);
  
  const [isLoading, setIsLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState('');
  
  const [paidById, setPaidById] = useState('');
  const [amount, setAmount] = useState('');
  const [itemName, setItemName] = useState('');
  const [involvedMemberIds, setInvolvedMemberIds] = useState([]);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [editingTransactionId, setEditingTransactionId] = useState(null);
  const [isSavingEdit, setIsSavingEdit] = useState(false);

  const [isRecapModalOpen, setIsRecapModalOpen] = useState(false);
  const [selectedRecapMemberId, setSelectedRecapMemberId] = useState('');
  const [tempRecapMemberId, setTempRecapMemberId] = useState('');

  const confirmRecapMember = () => {
    if (tempRecapMemberId) {
      setSelectedRecapMemberId(tempRecapMemberId);
      setIsRecapModalOpen(false);
    }
  };

  const fetchData = async () => {
    if (!activityId) {
      setIsLoading(false);
      return;
    }

    try {
      const res = await api.getActivity(activityId);
      if (res.success) {
        setActivity(res.data.activity);
        setMembers(res.data.members);
        
        const sortedTrans = res.data.transactions.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
        setTransactions(sortedTrans);
      } else {
        setErrorMsg('Kegiatan tidak ditemukan atau link tidak valid.');
      }
    } catch (err) {
      setErrorMsg('Terjadi kesalahan koneksi saat memuat data.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activityId]);

  const toggleMemberInvolved = (id) => {
    setInvolvedMemberIds(prev => 
      prev.includes(id) ? prev.filter((mId) => mId !== id) : [...prev, id]
    );
  };

  const selectAllMembers = () => {
    setInvolvedMemberIds(members.map(m => m.id));
  };

  const clearMembers = () => {
    setInvolvedMemberIds([]);
  };

  const getMemberName = (id) => {
    const member = members.find((m) => String(m.id) === String(id));
    return member ? member.name : 'Unknown';
  };

  const formatRupiah = (number) => {
    if (!number) return 'Rp 0';
    return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(number);
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return '-';
    const date = new Date(dateStr);
    return new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(date);
  };

  const settlement = useMemo(() => {
    if (members.length === 0 || transactions.length === 0) return [];
    
    let balances = {};
    members.forEach(m => balances[m.id] = 0);
    
    transactions.forEach(t => {
      const paidBy = t.paid_by_member_id;
      const amountVal = parseFloat(t.amount);
      const involvedStr = t.involved_member_ids;
      
      let involvedIds = [];
      if (typeof involvedStr === 'string' && involvedStr.trim() !== '') {
        involvedIds = involvedStr.split(',').map(s => s.trim()).filter(s => s);
      } else if (Array.isArray(involvedStr)) {
        involvedIds = involvedStr;
      }
      
      if (involvedIds.length === 0) return;
      
      const splitAmount = amountVal / involvedIds.length;
      
      if (balances[paidBy] !== undefined) {
        balances[paidBy] += amountVal;
      }
      
      involvedIds.forEach(id => {
        if (balances[id] !== undefined) {
          balances[id] -= splitAmount;
        }
      });
    });
    
    let debtors = [];
    let creditors = [];
    
    for (const [id, balance] of Object.entries(balances)) {
      if (balance < -0.01) debtors.push({ id, amount: Math.abs(balance) });
      else if (balance > 0.01) creditors.push({ id, amount: balance });
    }
    
    debtors.sort((a, b) => b.amount - a.amount);
    creditors.sort((a, b) => b.amount - a.amount);
    
    let results = [];
    let i = 0, j = 0;
    
    while (i < debtors.length && j < creditors.length) {
      let debtor = debtors[i];
      let creditor = creditors[j];
      
      let minAmount = Math.min(debtor.amount, creditor.amount);
      
      const debtorObj = members.find(m => String(m.id) === String(debtor.id));
      const creditorObj = members.find(m => String(m.id) === String(creditor.id));
      
      if (debtorObj && creditorObj) {
        results.push({
          from: debtorObj.name,
          to: creditorObj.name,
          amount: minAmount,
          bankName: creditorObj.bank_name,
          bankAccount: creditorObj.bank_account
        });
      }
      
      debtor.amount -= minAmount;
      creditor.amount -= minAmount;
      
      if (debtor.amount < 0.01) i++;
      if (creditor.amount < 0.01) j++;
    }
    
    return results;
  }, [members, transactions]);

  const totalExpense = useMemo(() => {
    return transactions.reduce((sum, t) => sum + parseFloat(t.amount || 0), 0);
  }, [transactions]);

  const topContributor = useMemo(() => {
    if (transactions.length === 0 || members.length === 0) return null;
    const contributions = {};
    transactions.forEach(t => {
      contributions[t.paid_by_member_id] = (contributions[t.paid_by_member_id] || 0) + Number(t.amount);
    });
    
    let topId = null;
    let maxAmount = 0;
    for (const [id, amt] of Object.entries(contributions)) {
      if (amt > maxAmount) {
        maxAmount = amt;
        topId = id;
      }
    }
    
    const member = members.find(m => String(m.id) === String(topId));
    return member ? { name: member.name, amount: maxAmount } : null;
  }, [transactions, members]);

  const spendersRanking = useMemo(() => {
    if (transactions.length === 0 || members.length === 0) return [];
    
    const expenses = {};
    members.forEach(m => expenses[m.id] = 0);
    
    transactions.forEach(t => {
      const amt = Number(t.amount);
      const involvedStr = t.involved_member_ids;
      let involved = [];
      if (typeof involvedStr === 'string' && involvedStr.trim() !== '') {
        involved = involvedStr.split(',').map(s => s.trim()).filter(s => s);
      } else if (Array.isArray(involvedStr)) {
        involved = involvedStr;
      }
      if (involved.length === 0) return;
      const splitAmt = amt / involved.length;
      
      involved.forEach(id => {
        if (expenses[id] !== undefined) {
          expenses[id] += splitAmt;
        }
      });
    });
    
    return members
      .map(m => ({ id: m.id, name: m.name, amount: expenses[m.id] }))
      .filter(m => m.amount > 0)
      .sort((a, b) => b.amount - a.amount);
  }, [transactions, members]);

  const recapData = useMemo(() => {
    if (!selectedRecapMemberId || transactions.length === 0 || members.length === 0) return null;
    
    const member = members.find(m => String(m.id) === String(selectedRecapMemberId));
    if (!member) return null;
    
    const items = [];
    let total = 0;
    
    transactions.forEach(t => {
      const involvedStr = t.involved_member_ids;
      let involved = [];
      if (typeof involvedStr === 'string' && involvedStr.trim() !== '') {
        involved = involvedStr.split(',').map(s => s.trim()).filter(s => s);
      } else if (Array.isArray(involvedStr)) {
        involved = involvedStr;
      }
      
      if (involved.includes(String(member.id))) {
        const splitAmt = Number(t.amount) / involved.length;
        items.push({
          name: t.item_name && t.item_name !== '-' ? t.item_name : 'Pengeluaran',
          amount: splitAmt
        });
        total += splitAmt;
      }
    });
    
    return {
      member: member,
      items: items,
      total: total
    };
  }, [selectedRecapMemberId, transactions, members]);

  const submitTransaction = async () => {
    if (!paidById || !amount || involvedMemberIds.length === 0) {
      toast("Mohon lengkapi form transaksi.", "error");
      return;
    }
    
    setIsSubmitting(true);
    try {
      const res = await api.addTransaction({
        activity_id: activityId,
        paid_by_member_id: paidById,
        amount: amount,
        item_name: itemName,
        involved_member_ids: involvedMemberIds
      });
      
      if (res.success) {
        setPaidById('');
        setAmount('');
        setItemName('');
        setInvolvedMemberIds([]);
        await fetchData();
        toast("Pengeluaran berhasil ditambahkan!", "success");
      } else {
        toast("Gagal menambahkan transaksi: " + res.error, "error");
      }
    } catch (err) {
      toast("Terjadi kesalahan koneksi.", "error");
      console.error(err);
    } finally {
      setIsSubmitting(false);
    }
  };

  const startEditTransaction = (t) => {
    setEditingTransactionId(t.id);
    setPaidById(t.paid_by_member_id);
    setAmount(t.amount);
    setItemName(t.item_name !== '-' ? t.item_name : '');
    
    const involved = typeof t.involved_member_ids === 'string' 
      ? t.involved_member_ids.split(',') 
      : t.involved_member_ids;
    setInvolvedMemberIds(involved);
  };

  const cancelEditTransaction = () => {
    setEditingTransactionId(null);
    setPaidById('');
    setAmount('');
    setItemName('');
    setInvolvedMemberIds([]);
  };

  const saveEditTransaction = async () => {
    if (!paidById || !amount || involvedMemberIds.length === 0) {
      toast("Mohon lengkapi form transaksi.", "error");
      return;
    }

    setIsSavingEdit(true);
    try {
      const res = await api.editTransaction({
        transaction_id: editingTransactionId,
        paid_by_member_id: paidById,
        amount: amount,
        item_name: itemName,
        involved_member_ids: involvedMemberIds
      });
      
      if (res.success) {
        cancelEditTransaction();
        await fetchData();
        toast("Transaksi berhasil disimpan!", "success");
      } else {
        toast("Gagal menyimpan transaksi: " + res.error, "error");
      }
    } catch (err) {
      toast("Terjadi kesalahan koneksi.", "error");
      console.error(err);
    } finally {
      setIsSavingEdit(false);
    }
  };

  const deleteTransaction = async (id) => {
    if (window.confirm('Yakin ingin menghapus pengeluaran ini?')) {
      try {
        const res = await api.deleteTransaction(id);
        if (res.success) {
          toast("Transaksi berhasil dihapus.", "success");
          await fetchData();
        } else {
          toast('Gagal menghapus: ' + (res.error || 'Unknown error'), 'error');
        }
      } catch (err) {
        toast('Terjadi kesalahan koneksi.', 'error');
      }
    }
  };

  const copyAccount = (account) => {
    if (!account) return;
    navigator.clipboard.writeText(account);
    toast("Nomor rekening disalin!", "success");
  };

  if (isLoading) {
    return <div className="text-center py-4 text-secondary" style={{ marginTop: '2rem' }}>Memuat data kegiatan...</div>;
  }

  if (!activityId) {
    return (
      <div className="card text-center" style={{ marginTop: '2rem', padding: '3rem 1.5rem' }}>
        <h2 className="card-title">Selamat Datang di SplitBill</h2>
        <p className="text-secondary mb-4" style={{ maxWidth: '400px', margin: '0 auto 2rem' }}>
          Minta link kegiatan dari temanmu untuk melihat tagihan, atau masuk ke area admin untuk membuat kegiatan baru.
        </p>
        <Link to="/admin" className="btn btn-primary" style={{ display: 'inline-flex' }}>
          Masuk ke Area Admin
        </Link>
      </div>
    );
  }

  if (errorMsg) {
    return (
      <div className="card text-center text-danger" style={{ marginTop: '2rem' }}>
        <h2 className="card-title text-danger">Oops!</h2>
        <p>{errorMsg}</p>
      </div>
    );
  }

  return (
    <div>
      <div className="card mb-4 text-center">
        <h2 className="card-title mb-2" style={{ fontSize: '1.75rem' }}>{activity?.name}</h2>
        <p className="text-secondary mb-0">Status: <span className={`badge ${activity?.status === 'active' ? 'badge-success' : 'badge-secondary'}`}>{activity?.status === 'active' ? 'Aktif' : 'Selesai'}</span></p>
        <p className="text-secondary mt-1" style={{ fontSize: '0.875rem' }}>Dibuat pada: {formatDate(activity?.created_at)}</p>
      </div>

      <div className="summary-cards-container mb-4 mt-4">
        <div className="card summary-card" style={{ background: 'linear-gradient(135deg, #f79039, #e65c00)', color: 'white', border: 'none', padding: '1.5rem' }}>
          <h4 style={{ color: 'white', opacity: 0.9 }}>Total Pengeluaran</h4>
          <div className="amount" style={{ color: 'white' }}>{formatRupiah(totalExpense)}</div>
        </div>
        <div className="card summary-card" style={{ background: 'linear-gradient(135deg, #10B981, #059669)', color: 'white', border: 'none', padding: '1.5rem' }}>
          <h4 style={{ color: 'white', opacity: 0.9 }}>Kontributor Terbanyak</h4>
          {topContributor ? (
            <div>
              <div className="amount" style={{ fontSize: '1.25rem', color: 'white' }}>{topContributor.name}</div>
              <div style={{ fontSize: '0.875rem', opacity: 0.9, color: 'white' }}>{formatRupiah(topContributor.amount)}</div>
            </div>
          ) : (
            <div style={{ opacity: 0.8, color: 'white' }}>Belum ada</div>
          )}
        </div>
      </div>

      <div className="card mb-4 text-center">
        <p className="mb-3 font-semibold text-secondary" style={{ fontWeight: 600 }}>Ingin melihat rincian belanjamu?</p>
        <button className="btn btn-secondary" onClick={() => setIsRecapModalOpen(true)}>Klik Disini</button>
      </div>

      {recapData && (
        <div className="card mb-4">
          <div className="recap-header">
            <h3 className="card-title mb-0">Rekap Belanjaan: {recapData.member.name}</h3>
            <button className="btn btn-secondary btn-sm" onClick={() => setSelectedRecapMemberId('')}>Tutup</button>
          </div>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', minWidth: '300px' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--border)' }}>
                  <th style={{ padding: '0.75rem', fontWeight: 600 }}>Nama Aktivitas</th>
                  <th style={{ padding: '0.75rem', fontWeight: 600, textAlign: 'right' }}>Biaya</th>
                </tr>
              </thead>
              <tbody>
                {recapData.items.map((item, idx) => (
                  <tr key={idx} style={{ borderBottom: '1px solid var(--border)' }}>
                    <td style={{ padding: '0.75rem' }}>{item.name}</td>
                    <td style={{ padding: '0.75rem', textAlign: 'right' }}>{formatRupiah(item.amount)}</td>
                  </tr>
                ))}
                {recapData.items.length === 0 && (
                  <tr>
                    <td colSpan="2" style={{ padding: '1rem', textAlign: 'center', color: 'var(--secondary)' }}>Tidak ada pengeluaran.</td>
                  </tr>
                )}
              </tbody>
              <tfoot>
                <tr>
                  <td style={{ padding: '0.75rem', fontWeight: 700 }}>Total</td>
                  <td style={{ padding: '0.75rem', textAlign: 'right', fontWeight: 700, color: 'var(--danger)' }}>{formatRupiah(recapData.total)}</td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      )}

      <div className="grid grid-cols-2">
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <div className="card" style={{ flex: 1, border: editingTransactionId ? '2px solid var(--primary)' : '' }}>
            <h2 className="card-title">
              {editingTransactionId ? 'Edit Pengeluaran' : 'Catat Pengeluaran Baru'}
            </h2>
            
            <div className="form-group">
              <label className="form-label">Nama Barang / Pengeluaran (Opsional)</label>
              <input 
                type="text" 
                value={itemName} 
                onChange={(e) => setItemName(e.target.value)}
                className="form-control" 
                placeholder="Contoh: Tiket Masuk, Makan Siang" 
              />
            </div>
            
            <div className="form-group">
              <label className="form-label">Siapa yang bayar?</label>
              <select value={paidById} onChange={(e) => setPaidById(e.target.value)} className="form-control">
                <option value="" disabled>Pilih anggota...</option>
                {members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}
              </select>
            </div>
            
            <div className="form-group">
              <label className="form-label">Berapa totalnya? (Rp)</label>
              <input 
                type="number" 
                value={amount} 
                onChange={(e) => setAmount(e.target.value)}
                className="form-control" 
                placeholder="0" 
              />
            </div>
            
            <div className="form-group">
              <label className="form-label mb-2">Siapa saja yang ikut patungan?</label>
              <div className="mb-2" style={{ display: 'flex', gap: '0.5rem' }}>
                <button onClick={selectAllMembers} className="btn btn-secondary btn-sm" style={{ padding: '0.25rem 0.75rem', fontSize: '0.75rem' }}>Pilih Semua</button>
                <button onClick={clearMembers} className="btn btn-secondary btn-sm" style={{ padding: '0.25rem 0.75rem', fontSize: '0.75rem' }}>Bersihkan</button>
              </div>
              <div className="checkbox-grid">
                {members.map(m => (
                  <label key={m.id} className="toggle-switch">
                    <input 
                      type="checkbox" 
                      checked={involvedMemberIds.includes(m.id)} 
                      onChange={() => toggleMemberInvolved(m.id)}
                    />
                    <span className="toggle-slider"></span>
                    <span className="toggle-label">{m.name}</span>
                  </label>
                ))}
              </div>
            </div>
            
            {editingTransactionId ? (
              <div style={{ display: 'flex', gap: '0.5rem', marginTop: '1.5rem' }}>
                <button onClick={saveEditTransaction} className="btn btn-primary" style={{ flex: 1 }} disabled={isSavingEdit}>
                  <Save size={20} /> {isSavingEdit ? 'Menyimpan...' : 'Simpan'}
                </button>
                <button onClick={cancelEditTransaction} className="btn btn-secondary">Batal</button>
              </div>
            ) : (
              <button onClick={submitTransaction} className="btn btn-primary btn-block mt-4" disabled={isSubmitting || activity?.status !== 'active'}>
                <Save size={20} /> {isSubmitting ? 'Menyimpan...' : 'Simpan Pengeluaran'}
              </button>
            )}
            
            {activity?.status !== 'active' && !editingTransactionId && (
              <p className="text-danger mt-2" style={{ fontSize: '0.875rem' }}>Kegiatan sudah selesai. Tidak bisa menambah pengeluaran baru.</p>
            )}
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <div className="card" style={{ flex: 1, backgroundColor: 'var(--primary)', color: 'white', border: 'none' }}>
            <h2 className="card-title" style={{ color: 'white', background: 'none', WebkitTextFillColor: 'initial' }}>Tagihan & Pembayaran</h2>
            
            <div className="settlement-summary mb-4 p-4" style={{ backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 'var(--radius)' }}>
              <p className="mb-1" style={{ fontSize: '0.875rem', opacity: 0.9 }}>Total Pengeluaran Kegiatan</p>
              <h3 style={{ fontSize: '1.75rem', margin: 0 }}>{formatRupiah(totalExpense)}</h3>
            </div>
            
            <h3 style={{ fontSize: '1.1rem', marginBottom: '1rem' }}>Siapa Bayar ke Siapa?</h3>
            
            {settlement.length === 0 ? (
              <p style={{ opacity: 0.8 }}>Belum ada tagihan.</p>
            ) : (
              <div className="settlement-list">
                {settlement.map((s, index) => (
                  <div key={index} className="settlement-item">
                    <div className="settlement-route">
                      <strong>{s.from}</strong> <span style={{ opacity: 0.7 }}>bayar ke</span> <strong>{s.to}</strong>
                    </div>
                    <div className="settlement-amount">
                      {formatRupiah(s.amount)}
                    </div>
                    {s.bankAccount && (
                      <div className="settlement-action">
                        <div className="account-badge">
                          <span className="badge-orange">{s.bankName || 'Rekening/E-Wallet'}</span>
                          {s.bankAccount}
                        </div>
                        <button onClick={() => copyAccount(s.bankAccount)} className="btn-copy" title="Copy Nomor">
                          <Copy size={14} />
                        </button>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="card mt-4">
        <h2 className="card-title">Daftar Pengeluaran</h2>
        {transactions.length === 0 ? (
          <p className="text-secondary">Belum ada pengeluaran dicatat.</p>
        ) : (
          <div className="transaction-history">
            {transactions.map(t => (
              <div key={t.id} className="transaction-item" style={{ marginBottom: '1rem', padding: '1rem', border: '1px solid var(--border)', borderRadius: '8px', background: 'var(--background)' }}>
                <div className="transaction-header">
                  <div className="transaction-info">
                    <strong>{getMemberName(t.paid_by_member_id)}</strong> 
                    <span className="text-secondary"> menalangi </span>
                    <strong className="text-primary">{formatRupiah(t.amount)}</strong>
                    <span className="text-secondary"> untuk </span>
                    <strong>{t.item_name !== '-' ? t.item_name : 'Pengeluaran'}</strong>
                    
                    <div className="transaction-date mt-1" style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>
                      {formatDate(t.created_at)}
                    </div>
                    
                    <div className="transaction-involved mt-2">
                      <span className="text-secondary" style={{ fontSize: '0.75rem' }}>Ditanggung oleh: </span>
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.25rem', marginTop: '0.25rem' }}>
                        {typeof t.involved_member_ids === 'string' 
                          ? t.involved_member_ids.split(',').map((id, idx) => (
                              <span key={idx} className="badge badge-secondary" style={{ fontSize: '0.7rem' }}>
                                {getMemberName(id.trim())}
                              </span>
                            ))
                          : (t.involved_member_ids || []).map((id, idx) => (
                              <span key={idx} className="badge badge-secondary" style={{ fontSize: '0.7rem' }}>
                                {getMemberName(id)}
                              </span>
                            ))
                        }
                      </div>
                    </div>
                  </div>
                  {activity?.status === 'active' && (
                    <div className="transaction-actions" style={{ display: 'flex', gap: '0.5rem', marginTop: '0.5rem' }}>
                      <button onClick={() => startEditTransaction(t)} className="btn btn-secondary btn-sm" style={{ padding: '0.4rem 0.75rem', color: 'var(--primary)' }} title="Edit">
                        <Edit size={16} /> Edit
                      </button>
                      <button onClick={() => deleteTransaction(t.id)} className="btn btn-secondary btn-sm" style={{ padding: '0.4rem 0.75rem', color: 'var(--danger)' }} title="Hapus">
                        <Trash2 size={16} /> Hapus
                      </button>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {spendersRanking.length > 0 && (
        <div className="card mb-4">
          <h3 className="card-title">Ranking Pengeluaran Terbanyak</h3>
          <p className="text-secondary mb-4" style={{ fontSize: '0.875rem' }}>Urutan anggota berdasarkan total tagihan (pengeluaran).</p>
          
          <div className="ranking-list">
            {spendersRanking.map((spender, index) => (
              <div key={spender.id} className="ranking-item">
                <div className="ranking-rank">
                  {index === 0 ? <span style={{ fontSize: '1.5rem' }} title="Peringkat 1">🥇</span> :
                   index === 1 ? <span style={{ fontSize: '1.5rem' }} title="Peringkat 2">🥈</span> :
                   index === 2 ? <span style={{ fontSize: '1.5rem' }} title="Peringkat 3">🥉</span> :
                   <span className="rank-number">{index + 1}</span>}
                </div>
                <div className="ranking-name" style={{ flex: 1, fontWeight: 600 }}>{spender.name}</div>
                <div className="ranking-amount" style={{ fontWeight: 700, color: 'var(--danger)' }}>{formatRupiah(spender.amount)}</div>
              </div>
            ))}
          </div>
        </div>
      )}
      
      <div className="app-footer">
        <Link to="/admin" className="admin-link">Area Admin</Link>
      </div>

      {isRecapModalOpen && (
        <div className="modal-overlay" onClick={(e) => { if (e.target === e.currentTarget) setIsRecapModalOpen(false); }}>
          <div className="modal-content card" style={{ padding: '2rem' }}>
            <h3 className="card-title" style={{ marginBottom: '0.5rem' }}>Pilih Anggota</h3>
            <p className="text-secondary mb-4">Siapa yang ingin dilihat rekap belanjanya?</p>
            <div className="form-group">
              <select value={tempRecapMemberId} onChange={(e) => setTempRecapMemberId(e.target.value)} className="form-control">
                <option value="" disabled>Pilih Anggota</option>
                {members.map(m => (
                  <option key={m.id} value={m.id}>{m.name}</option>
                ))}
              </select>
            </div>
            <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'flex-end', marginTop: '1.5rem' }}>
              <button className="btn btn-secondary" onClick={() => setIsRecapModalOpen(false)}>Batal</button>
              <button className="btn btn-primary" onClick={confirmRecapMember}>Lihat Rekap</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
